export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_SUCCESS';

export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_NEXT_EXERCISE = 'SET_NEXT_EXERCISE';
