export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const GET_EXERCISE_REQUEST = 'GET_EXERCISE_REQUEST';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAILURE = 'GET_EXERCISE_FAILURE';

export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS';
export const UPDATE_EXERCISE_FAILURE = 'UPDATE_EXERCISE_FAILURE';
export const COMPLETE_LESSON_SUCCESS = 'COMPLETE_LESSON_SUCCESS';
export const COMPLETE_LESSON_FAILURE = 'COMPLETE_LESSON_FAILURE';

export const POST_GET_EXERCISE_SUCCESS = 'POST_GET_EXERCISE_SUCCESS';

export const SYNC_EXERCISES = 'SYNC_EXERCISES';

export const SET_CORRECT = 'SET_CORRECT';

export const FINISH_EXERCISE = 'FINISH_EXERCISE';
