export const GET_PROGRESS_SUCCESS = 'GET_PROGRESS_SUCCESS';
export const GET_PROGRESS_FAILURE = 'GET_PROGRESS_FAILURE';

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';

export const SET_TOTAL = 'SET_TOTAL';
